markdown: kramdown
title: Example blog.
description: This example blog demonstrates this custom theme.
baseurl: /custom-gitpages-theme # set this to the part in capitals (/BASEURL in http://www.example.com/BASEURL/post1)
permalink: /:year/:month/:day/:title:output_ext
gist:
  noscript: false
collections:
  mainpages:
    output: true
  category:
    output: true
js_dir: "/assets/js"
defaults:
  -
    values:
      author: "wnuke" # Replace this by your author name.
      author-github-url: "https://github.com/wnuke/" # Replace this url with your github url.
plugins:
  - jekyll-feed
analytics-url: "" # your google analytics URL
analytics-id: "" # your google analytics id
